### ISSUE TITLE
Vilte Call  Venc/Vdec  issue

### ISSUE THREAD

**Issue by anandsvm** [Nicklas373/kernel_xiaomi_msm8953-4.9#6]
![qcom](https://user-images.githubusercontent.com/71373806/102962361-b4ca1a00-450c-11eb-95be-1cc210ad67fb.png)
Hello Sir, Getting this error while vilte call(operator video call ) in Redmi Note 4. Tried to switch to other omx codec getting same error always. The video of other caller looks fine in my mobile. But when the my video in other device is low quality and have green color filled 20% of screen.

**Comment by Rafiester** [comment]
i dont think this is a kernel issue, based on ur logs its "qcom.decoder.avc" so its came from rom (Media Codec), Did u already tried to change other kernel and make sure vilte work on it ?

**Comment by Nicklas373** [comment]
This is actually media codec issue (google one), i'm not sure this is a kernel related issue. Make sure if that vilte work on other kernel, if same then this aren't kernel issue. Since i can't test it by myself.

@anandsvm

**Comment by anandsvm** [comment]
Sir Fixed . It was Due to Latest Android 11 Update. Thank you Sir. Vilte issue also fixed by Zeelog SIr :). It is working fine now :)

**Comment by Nicklas373** [comment]
Well okay then i know this is are actually from ROM side issue, not kernel. So I'll close this issue now
