### ISSUE TITLE
OC kernel for Q

### ISSUE THREAD

**Issue by Alex1Senpai** [Nicklas373/kernel_xiaomi_msm8953-4.9#7]
Can I wait for the overclocking of the kernel on Q?
Also, the without overclocking kernel is very hot  .

**Comment by Nicklas373** [comment]
Overclocking actually possible to do, and i already did that in other source. I won't bring that to public release since there's so much guide outside for how to do it.

For heat, just need to make sure your thermal control your device correctly.

**Comment by alanndz** [comment]
@Nicklas373 Ok
